"""empty message

Revision ID: 4a3c9f0c079e
Revises: 2b04eaaefedd
Create Date: 2023-12-07 13:28:18.005774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3c9f0c079e'
down_revision = '2b04eaaefedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(), nullable=True))
    op.drop_column('messages', 'message_body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_body', sa.VARCHAR(), nullable=True))
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
