"""empty message

Revision ID: caa29d9999b7
Revises: b4c7291c291a
Create Date: 2023-12-07 13:22:45.800088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa29d9999b7'
down_revision = 'b4c7291c291a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_body', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
